// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZZyPZR6-3_YPvfk0ZDKMT-55wTB7dqHg',
    appId: '1:446761754287:web:123d456d6a9cee1d567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flickchat-c2d04',
    authDomain: 'flickchat-c2d04.firebaseapp.com',
    storageBucket: 'flickchat-c2d04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjbA4kSWrX2NXl03eR-_g04Ycy4kuQ9Ro',
    appId: '1:446761754287:android:f987148ccc6d9d35567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flickchat-c2d04',
    storageBucket: 'flickchat-c2d04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxYrNx73Goxz0y7VOphyT8bRjJ2-5--rw',
    appId: '1:446761754287:ios:b6b91f7223610c55567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flickchat-c2d04',
    storageBucket: 'flickchat-c2d04.firebasestorage.app',
    iosBundleId: 'com.example.flikchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxYrNx73Goxz0y7VOphyT8bRjJ2-5--rw',
    appId: '1:446761754287:ios:b6b91f7223610c55567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flickchat-c2d04',
    storageBucket: 'flickchat-c2d04.firebasestorage.app',
    iosBundleId: 'com.example.flikchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZZyPZR6-3_YPvfk0ZDKMT-55wTB7dqHg',
    appId: '1:446761754287:web:5b7a187a3d8173b7567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flickchat-c2d04',
    authDomain: 'flickchat-c2d04.firebaseapp.com',
    storageBucket: 'flickchat-c2d04.firebasestorage.app',
  );
}
