// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA*****************dqHg',
    appId: '1:4467617******************567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flic***********4',
    authDomain: 'flic***************om',
    storageBucket: 'flickc************app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA*****************dqHgo',
    appId: '1:446761*****************6d9d35567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flic*****************04',
    storageBucket: 'flickc*****************ge.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy*****************RjJ2-5--rw',
    appId: '1:4467617*****************10c55567e5a',
    messagingSenderId: '446761754287',
    projectId: 'flic*****************04',
    storageBucket: 'flick*****************ge.app',
    iosBundleId: 'com.e*****************ikchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx*****************2-5--rw',
    appId: '1:44676*****************0c*****************e5a',
    messagingSenderId: '446761754287',
    projectId: 'flickc*****************4',
    storageBucket: 'flick*****************storage.app',
    iosBundleId: 'com.e*****************hat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaS*****************B7*****************g',
    appId: '1:446*****************e5a',
    messagingSenderId: '446761754287',
    projectId: 'fl*****************04',
    authDomain: 'fli*****************om',
    storageBucket: 'flickcha*****************p',
  );
}
